configured_endpoints: 20
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/jonluca%2Fweights-ab56c0234691dbfdae25a44d59d0e5eb0c722dba0fb1bc7667cc26d80bd9dd40.yml
openapi_spec_hash: cf33c6febcfce696d0ac3f3470d4b432
config_hash: 35992a0b4d2287b69b30a6dfbdaaec5f
