configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/jonluca%2Fweights-1abc5afcc130be72f496cae6dabef522b48cc56ca056bb2bb98cddb1752d831b.yml
openapi_spec_hash: 15c7eef901a216ec7886d9d19c4249dd
config_hash: fbe9d4323bcb9e3a567cb74748fef0c0
